### ISSUE TITLE
Css positioning

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#10]
Position: absolute - нужно по-максимум избегать и использовать только в крайних случаях или в специально для этого предназначенных кейсах . На скрине ниже - явно можно обойтись без этого. И ещё в нескольих местах точно видел. 
![image](https://user-images.githubusercontent.com/44312820/91558181-0cda8080-e960-11ea-9dee-ba2b8e31ceed.png)

**Comment by Nirall** [comment]
Подправил, хотя по-моему здесь лучше бы оставить. Это просто декоративный текстовой блок, в основном потоке документа он скорее мешать будет.
Абсолютное позиционирование также использую в блоках:
- checkbox-item, toggle-button для стилизации стандартного чекбокса;
- dropdown для выпадающего меню, чтобы не сдвигал следующие за ним элементы а перекрывал их;
- navbar для позиционирования схлопнутого навиг.меню на узких экранах;
- pie-chart для количества голосов в центре графика;
- registration для расположения форм (по макету они перекрывают друг друга).
Здесь вроде использование вполне оправдано.
