### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#11]
Весь JS код должен быть реализован классами.
Название класса должно совпадать с названием блока, но с большой буквы, т.к. все классы именуются с большой буквы.

**Comment by Nirall** [comment]
Подправил

**Comment by Feinminen** [comment]
> Подправил. Обернул код соответствующим классом и реализовал все в методе init(), или так не пойдет?

В целом, такая реализация пойдёт, но у тебя сейчас init - статик метод и по факту он вообще ни как не относится к экземпляру класса, т.к. статик сайд класса к инстансу никакого отношения не имеет.
Нужно сделать так, чтобы сначала создавался экземпляр класса, а потом уже инитилиось всё что нужно (либо инитилось сразу при создании экземпляра класса).

**Comment by Nirall** [comment]
Сделал через init при создании

**Comment by Feinminen** [comment]
Все файлы, которые ипортируют классы - тоже должны начинаться с большой буквы.

Сейчас в проекте используется досаточно большое количество предохранителей типа try catch - но зачем они нужны - не совсем понятно. Т.к. никакой пользы как таковой они не несут.
Ты же можешь просто проверять в инит методе есть ли такой элемент и если его нет - ничего не делать. И никаких ошибок в принципе не будет :)

Все кавычки в JS файлах должны быть одинарными, также как и в css/scss, а в pug двойными. Но при этом, если в JS имеются вставки для PUG (например, атрибудты) - там остаются двойные кавычки, как было в PUG.
![image](https://user-images.githubusercontent.com/44312820/93735910-c5ff4400-fc08-11ea-93de-5493db734af1.png)
Тут немного вырвано из контеста, но в целом понятно) [ссылка на ишью](https://github.com/fullstack-development/front-end-best-practices/issues/48)

**Comment by Nirall** [comment]
> Ты же можешь просто проверять в инит методе есть ли такой элемент и если его нет - ничего не делать. И никаких ошибок в принципе не будет :)

Да, так логичней будет )). Сделал проверку при создании экземпляра класса, или лучше все-таки в init() поместить?

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94225424-1cc59000-ff1f-11ea-842c-4162ef314e1a.png)
У тебя сейчас поиск элементов идёт в документе, а не в блоке и следовательно, если у тебя на странице будет несколько одинаковых блоков, то всё сломается, т.к. JS будет применяться только для первых в потоке элементов.

Насчёт проверок, лучше сделать проверку на этапе создания экземпляра и внутри класса на наличие немобходимых элементов, т.к. форма регистрации, допустим, будет, а вот элементов каких-то в ней будет нехватать.

**Comment by Nirall** [comment]
Подправил. Но на странице регистрации поиск кнопок все равно осуществляется в документе, т.к. они в навбаре находятся

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94519502-d04abf00-0254-11eb-813c-a5a13f1925aa.png)
Класс и его инициализация всегда должны быть в разных файлах

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94521106-ac3cad00-0257-11eb-85e9-4038994d3c7c.png)
Зачем дважды тянуть с ДОМ-а узлы, если можно просто сделать:
```
const elements = document.querySelectorAll('.js-smth');
if(elements) do;
```

**Comment by Feinminen** [comment]
> Подправил. Но на странице регистрации поиск кнопок все равно осуществляется в документе, т.к. они в навбаре находятся

Не совсем понял причём тут вообще кнопки, которые в навбаре находятся, если у этих кнопок логика везде одинаковая, то локика вообще должна быть в блоках кнопок.
Т.е. кнопки навбара вообще никакого отношения не должны иметь к кнопкам в registration page

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94521970-143fc300-0259-11eb-9287-29dc3d005d68.png)
не совсем понял зачем || null для элементов, querySelector же и так null возвращает вроде, если элемент не найден

**Comment by Nirall** [comment]
> Не совсем понял причём тут вообще кнопки, которые в навбаре находятся, если у этих кнопок логика везде одинаковая, то локика вообще должна быть в блоках кнопок.
> Т.е. кнопки навбара вообще никакого отношения не должны иметь к кнопкам в registration page

Согласен, но т.к. формы регистрации и входа находятся только на странице регистрации, то тогда решил не выносить функционал за пределы страницы. Скритпы на отображение форм по клику сидят в кнопках из навбара, поиск элементов форм соответственно производится по документу.

> не совсем понял зачем || null для элементов, querySelector же и так null возвращает вроде, если элемент не найден

В голове просто сидело, что querySelector ошибку будет выкидывать а не null возвращать
