### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#12]
У тебя сейчас все картинки лежат в одной папке. Для каждого блока, в котором используются картинки - должна быть своя папка images и там, соответсвенно, должны лежать только картинки относящиеся к этому блоку. И импортиться они должны только в этом блоке.
(скрин для наглядности)
![image](https://user-images.githubusercontent.com/44312820/91558710-0d274b80-e961-11ea-8793-dee6c1eb5976.png)

Также все картинки/иконки нужно именовать так, чтобы было понятно что на них находится.

**Comment by Nirall** [comment]
Подправил
