### ISSUE TITLE
Scss / styles

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#13]
![image](https://user-images.githubusercontent.com/44312820/91559408-3e544b80-e962-11ea-8500-c6ffaca2fc66.png)
1) Пробел перед блоками не нужен

2) Для случаев, когда нужно использовать блок внутри, допустим, модификатора, можно использовать переменную - как на скрине, чтобы не копипастить блок. Название r - это код конвенш и сокращение от root, можно называть и r и root, но лучше на данном этапе именовать как root, имхо.
![image](https://user-images.githubusercontent.com/44312820/91559322-0d741680-e962-11ea-8661-3aa1b965e0bc.png)

3) Это чуть ниже по файлу
![image](https://user-images.githubusercontent.com/44312820/91559751-d8b48f00-e962-11ea-842e-f7613cfe2086.png)
Почему тут не ```&__rating-star```? :D

4)Нельзя использовать селекторы по тэгам, даже в таких случаях.
![image](https://user-images.githubusercontent.com/44312820/91559827-f8e44e00-e962-11ea-86bc-d0e6425f3636.png)

5)Для каждого html элемента должен быть свой класс. (это к предыдущему пункту)

6)Порой из-за trailing spaces(крансые пробелы у меня на скринах) могут быть проблемы, + на них линтер зачастую ругается. Для того чтобы наверняка не было проблем с ними - тоже можно использовать одноименное расширение для вскода 'trailing spaces'. Оно будет помечать их и при сохранении файла удалять

**Comment by Nirall** [comment]
> 3. Это чуть ниже по файлу
>    ![image](https://user-images.githubusercontent.com/44312820/91559751-d8b48f00-e962-11ea-842e-f7613cfe2086.png)
>    Почему тут не `&__rating-star`? :D

Для эмодзи-картинок локально подключаю Material Icons. Соответственно для некоторых элементов назначается 2 класса - material-icons и класс элемента (в данном случае apartment-card__img). Из -за автоматического импорта стилей порядок не определить (стиль .material-icons подключается в index.scss), поэтому для большего приоритета стиля класса элемента приходится делать более специфичный селектор. Как лучше исправить? Или лучше material-icons не использовать даже локально и все эмодзи подгружать картинками?

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/92345724-bce48200-f0f4-11ea-8ba7-9cc1a781092a.png)
Можно же подключать стили примерно вот так, чтобы порядок импортов был определён.

**Comment by Nirall** [comment]
Коммит совместный с issue #8 т.к. рефакторил  все блоки попутно исправляя, trailing space поставил
