### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#14]
Исправить все ошибки, которые логаются в консоль.
![image](https://user-images.githubusercontent.com/44312820/92347237-a987e580-f0f9-11ea-801c-2573aeb6ab3f.png)

**Comment by Nirall** [comment]
Основная часть исправлена в коммите по оборачиванию в классы, в этом коммите выловлены оставшиеся ошибки

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/93736070-6c4b4980-fc09-11ea-95e6-70518eff96c6.png)

**Comment by Nirall** [comment]
Подправил в коммите для issue #11.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94222967-f866b500-ff18-11ea-8a36-b056c5ac9588.png)

У меня сейчас вообще не работают календари, дропдауны  и т.д. - это на лендосе.

**Comment by Nirall** [comment]
Похоже криво закоммитил, в index.js поменял файлы скриптов datepicker'а чтобы начинались с заглавной, сами файлы в коммите не переименовал.

**Comment by Nirall** [comment]
ignorecase у гита выключил, задублированный js файлы убрал в коммите к ишью #11
