### ISSUE TITLE
Footers

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#18]
Сейчас в проетке есть 3 разных футера. 2 из которых имеют абсолютно идентичный PUG.
Нужно, по-хорошему, разделить их так, чтобы у футера была только обертка, а собирался они просто из разных блоков типа: socials, copyright и т.д.

**Comment by Feinminen** [comment]
Имхо, достаточно логично, что весь вот этот контент - должен быть одним целым блоком, который просто можно назвать footer или page-footer. Там же по отдельности нигде не используются large/medium/small футеры - это должна быть одна 'компонента', которая на маленьких размерах за счёт медиазапросов/модификаторов преобразуется к виду мобильного футера.
![image](https://user-images.githubusercontent.com/44312820/94517869-08e99900-0253-11eb-894e-a175d4031584.png)

И по структуре это всё примерно вот так выглядеть будет:
![image](https://user-images.githubusercontent.com/44312820/94518120-8a412b80-0253-11eb-8813-a5105bcfef8e.png)

1-е это большой футер на первом скрине, а 2-е - маленький.

**Comment by Nirall** [comment]
Объединил в один блок, перестройку сделал медиазапросами
