### ISSUE TITLE
UI-KIT

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#19]
На ui ките поплыли стили
![image](https://user-images.githubusercontent.com/44312820/94225291-c0627080-ff1e-11ea-9347-056d0f50c32e.png)

**Comment by Feinminen** [comment]
В карточках поплохело календарю
![image](https://user-images.githubusercontent.com/44312820/94517400-0b97be80-0252-11eb-958f-cf89477eb71f.png)
Таже не совсем понятно, почему сейчас очень у многих страниц фиксированные горизонтальные маргины, хотя там явно же должно быть выравнивание по центру

**Comment by Feinminen** [comment]
Также нужно добавить хотя бы минимальную респонсивность, чтобы вот такого не было, это в пару медиазапросов буквалаьно можно сделать.
![image](https://user-images.githubusercontent.com/44312820/94517453-2c601400-0252-11eb-8c0d-7a4eca7491ea.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94519855-78f91e80-0255-11eb-8d23-dd1479b0bf32.png)
Нельзя так называть элементы :)
Название должно отображать то что будет находится в элементе, и вообще, имхо, тут лушче это всё сделать модификаторами.
У тебя будет какой-то дефолтный элемент, допустим, text(для текста бади) и у него будут модификаторы _size_small/medium/large.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94520056-d2614d80-0255-11eb-85e7-63c2887e1b19.png)
И модификаторы по именам тэгов тоже называть нельзя

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94520177-ffadfb80-0255-11eb-8941-851bf00e3206.png)
Остался коммент со стилями

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94883624-4b9ab380-0495-11eb-9047-77ba755e73a7.png)
у кита не подключаются скрипты из-за регистра

**Comment by Feinminen** [comment]
У календаря сейчас очень странные ховеры на кнопки

**Comment by Nirall** [comment]
> у кита не подключаются скрипты из-за регистра

Если из-за некорректной работы кнопки "применить" на datepicker, то это из-за самого datepicker. А так у меня скрипты вроде норм отрабатывают
