### ISSUE TITLE
Event handlers

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#22]
Сейчас обработчики событий написаны не по стандартам:
 1) Их стоит выносить в отдельные именованные функции.
 2) В обработчиках работать не с контекстом (this), а с аргументом объекта ивента, который был передан свыше.
 3) Имена обработчикам событий нужно давать в формате handleElementNameEventName

[именование](https://github.com/fullstack-development/front-end-best-practices/blob/0eedda20077c13a9244b4364166f776ef046e871/JS/README.md#3.3)
[модульность](https://github.com/fullstack-development/front-end-best-practices/blob/0eedda20077c13a9244b4364166f776ef046e871/JS/README.md#1.13)

**Comment by Nirall** [comment]
> 2\. В обработчиках работать не с контекстом (this), а с аргументом объекта ивента, который был передан свыше.

Здесь не совсем понял, у нас же все классом обернуто. Зачастую в обработчике требуется доступ к экземпляру класса и  его методам, а через event.currentTarget вроде как можно только HTML элемент получить.
Частично подправил но у себя не вижу как без this обойтись можно.
