### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by iatsdotfatr** [Nirall/FSD_hotel#29]
1. Блоку не рекомендует устанавливать фиксированную геометрию. Если width в данном случае оправдана, то height нет.
![Screenshot from 2021-01-29 19-08-46](https://user-images.githubusercontent.com/51824674/106282225-7d1c6380-626a-11eb-8555-fc623155487b.png)

2. Здесь должен использоваться соответствующий блок из ui-kit (при наведении на звезды как минимум должен изменяться курсор, еще лучше, чтобы можно было переключать рейтинг)
![from uikit](https://user-images.githubusercontent.com/51824674/106282550-f320ca80-626a-11eb-89eb-3a9804ad0fc6.png)

**Comment by iatsdotfatr** [comment]
1. Не надо к одному css-классу добавлять несколько модификаторов.
![invalid modifier](https://user-images.githubusercontent.com/51824674/107919038-e56e8300-6f94-11eb-8c77-6fba9b822213.png)

2. Два блока в одном препроцессорном файле. Под каждый блок должна быть отдельная директория.
![two blocks in file](https://user-images.githubusercontent.com/51824674/107919314-4b5b0a80-6f95-11eb-8a24-a7c546edb92a.png)

3. Название директории и миксина не совпадает с названием bem-блока.
![block directory name](https://user-images.githubusercontent.com/51824674/107919147-0cc55000-6f95-11eb-9177-6f719d8e8f34.png)

**Comment by Nirall** [comment]
2. Разбивать на 2 блока не стал, сделал 2 элемента - граница и тело кнопки

**Comment by iatsdotfatr** [comment]
Двойной элемент. Ну и после js-классы должны дублировать БЭМ-классы.
![two els, mods](https://user-images.githubusercontent.com/51824674/108884969-6a126e80-7631-11eb-9dbb-1d0a9767c2d7.png)

**Comment by Nirall** [comment]
Сделал через разные классы для этих элементов, в CSS эти классы указал в одном правиле через запятую. Так же вроде тоже можно?

**Comment by iatsdotfatr** [comment]
> Сделал через разные классы для этих элементов, в CSS эти классы указал в одном правиле через запятую. Так же вроде тоже можно?

1. С точки зрения БЭМ, это один элемент, поэтому или модификаторы, или вообще не через классы.

2. Два элемента в одном.
![do](https://user-images.githubusercontent.com/51824674/109917183-14982a80-7cdf-11eb-9cc1-021dc7a7769e.png)
![dou2](https://user-images.githubusercontent.com/51824674/109917189-16fa8480-7cdf-11eb-96a6-317f203b14ad.png)
![doub](https://user-images.githubusercontent.com/51824674/109917193-18c44800-7cdf-11eb-85d2-015b71835a2f.png)
![doublee](https://user-images.githubusercontent.com/51824674/109917200-1b26a200-7cdf-11eb-8c4b-b812396cbff0.png)
![doubleel](https://user-images.githubusercontent.com/51824674/109917207-1e219280-7cdf-11eb-8c2d-4d152dc9bb35.png)

3. Внешнее позиционирование блока. Фиксированную высоту лучше тоже в элемент вынести.
![oute](https://user-images.githubusercontent.com/51824674/109917509-b0c23180-7cdf-11eb-8ae8-a81323d4ef62.png)
![outer pos](https://user-images.githubusercontent.com/51824674/109917516-b3248b80-7cdf-11eb-9664-b606c35ea71d.png)
![same out](https://user-images.githubusercontent.com/51824674/109917548-bc155d00-7cdf-11eb-8135-e44541ad84ea.png)
![same outer](https://user-images.githubusercontent.com/51824674/109917557-be77b700-7cdf-11eb-8481-2d11feff24b6.png)
![outer pos2 fx height](https://user-images.githubusercontent.com/51824674/109917565-c172a780-7cdf-11eb-8f0a-ca743674b408.png)
