### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#3]
Необходимо более подробно описать ридми, добавить команды для:
- клонирования репозитория
- установки зависимостей
- запуска дев мода
- запуска сборки билда
- развертывания проекта на GitHub Pages

Сейчас в проекте вообще нет команды для запуска девмода.(и даже самомго вебпак дев сервера нет)
Каким образом верстался макет без него? :D

**Comment by Nirall** [comment]
Подправил. Работал без сервера, билдил и запускал :).
