### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by iatsdotfatr** [Nirall/FSD_hotel#30]
1. На макете показано два состояния слайдера (галереи), обычное, то есть без стрелок и hover, когда стрелки появляются. Слайдер надо подключить / написать самому.
![Screenshot from 2021-01-29 19-52-21](https://user-images.githubusercontent.com/51824674/106283460-2879e800-626c-11eb-82e9-c553284d6af4.png)

2. Не следует устанавливать инлайновые стили без необходимости, здесь такой необходимости нет, достаточно использовать img-элемент, точнее элементы, см. выше.

3. И не надо использовать подобное позиционирование, padding изменяет размеры элемента, в данном случае это не нужно. Можно было бы использовать margin, только вместо больших значений (214px) проще было один из margin установить auto. Но после подключения слайдер и изменения элемента на img это все равно надо будет делать по-другому. И стрелки должны быть относительно, а не абсолютно, выровнены по центру картинки
![Screenshot from 2021-01-29 19-11-16](https://user-images.githubusercontent.com/51824674/106284794-db971100-626d-11eb-9da9-31efd7b80eb8.png)

**Comment by iatsdotfatr** [comment]
1. Удалить лишние стили.
![waste](https://user-images.githubusercontent.com/51824674/107227111-33d7cb00-6a45-11eb-951d-0d21323924d7.png)

2. Убрать фиксированную высоту.
![fixed height](https://user-images.githubusercontent.com/51824674/107227172-481bc800-6a45-11eb-846c-d9ba18b6113f.png)

3. У кнопки должна быть градиентная граница, согласно макету.
![grad border](https://user-images.githubusercontent.com/51824674/107227297-6a154a80-6a45-11eb-8717-51cbe35f1324.png)

4. А у чекбокса градиентная галочка
![gradient](https://user-images.githubusercontent.com/51824674/107227359-7b5e5700-6a45-11eb-92c4-7db648dac3b3.png)

5. При позиционировании соседних css-блоков (за исключением крайних) лучше использовать какой-то один вертикальный margin, top или bottom, чтобы минимизировать возможность margin-collapsing.
![margin bottom only](https://user-images.githubusercontent.com/51824674/107228155-882f7a80-6a46-11eb-9413-8a63b273d3bc.png)

6. Добавить запасные шрифты, соответствующие best-practices.
![no backup](https://user-images.githubusercontent.com/51824674/107228408-d775ab00-6a46-11eb-959e-0dfc9cdbc648.png)

7. Здесь, по сути, происходит дублирование стилей. Вместо этого, например, можно поместить элементы в один контейнер с соответствующими padding, а потом уже каждый из элементов подогнать под pixel perfect.
![repeating style no height](https://user-images.githubusercontent.com/51824674/107228988-7dc1b080-6a47-11eb-9ea5-4ce9a98a738b.png)

8. Тени слайдера взять с макета.
![shadows from](https://user-images.githubusercontent.com/51824674/107229121-9e8a0600-6a47-11eb-92bd-38113f63a660.png)

**Comment by iatsdotfatr** [comment]
> 5. При позиционировании соседних css-блоков (за исключением крайних) лучше использовать какой-то один вертикальный margin, top или bottom, чтобы минимизировать возможность margin-collapsing.
>    ![margin bottom only](https://user-images.githubusercontent.com/51824674/107228155-882f7a80-6a46-11eb-9413-8a63b273d3bc.png)

1. Я здесь в первую очередь имел ввиду блок apartment-form, где у некоторых соседних элементов есть margin, у некоторых нет, а у одного из элементов padding, вместо margin.

2. Отрицательные margin не использовать, согласно стандартам, конечно).
![negative margins](https://user-images.githubusercontent.com/51824674/107920053-80b42800-6f96-11eb-8bdb-e3857cbfa193.png)

3. Фиксированную высоту убрать.
![remove fixed height](https://user-images.githubusercontent.com/51824674/107920248-d38ddf80-6f96-11eb-8978-b736be255623.png)

4. Здесь тоже лучше padding заменить на margin, не надо увеличивать размеры элемента без причины. Ну и причин для фиксированной высоты здесь нет.
![pad to mrg](https://user-images.githubusercontent.com/51824674/107920354-07690500-6f97-11eb-802e-0b1819424916.png)

**Comment by Nirall** [comment]
4. Цвет у карточки отличается от фона, паддингом добирал до нужной высоты. У элемента rating убрал, но добавил к элементу content

**Comment by iatsdotfatr** [comment]
> 1. Паддингом добирал до нужной высоты. У элемента rating убрал, но добавил к элементу content

Норм. Тогда и margin-top на паддинг замени для последовательности.

> 1. Я здесь в первую очередь имел ввиду блок apartment-form, где у некоторых соседних элементов есть margin, у некоторых нет, а у одного из элементов padding, вместо margin.

1. В карточках сделай аналогично.

2. Здесь тоже позиционирование паддингами, на марджины замени.
![padds](https://user-images.githubusercontent.com/51824674/108883801-13586500-7630-11eb-87fc-04811ddcbfef.png)

3. Фиксированная высота.
![fixed height](https://user-images.githubusercontent.com/51824674/108883889-2a975280-7630-11eb-83f4-ea23760b53e9.png)

4. Просто -50% и элемент будет центрироваться вне зависимости от его размера.
![-50%](https://user-images.githubusercontent.com/51824674/108884126-6f22ee00-7630-11eb-923d-dc548b994f23.png)

**Comment by iatsdotfatr** [comment]
1. Здесь точно margin-left нужен?
![ml](https://user-images.githubusercontent.com/51824674/109917663-e830de00-7cdf-11eb-842a-b5a72341b479.png)

2. В данном случае неважно, но лучше тоже через margin задать верхний отступ.
![pad to marg](https://user-images.githubusercontent.com/51824674/109917759-0c8cba80-7ce0-11eb-93e4-66feb8197861.png)

**Comment by Nirall** [comment]
Через margin получается вот так
![image](https://user-images.githubusercontent.com/52122440/110280077-078b7c00-7ffc-11eb-89bb-1f1fafacd6d7.png)
