### ISSUE TITLE
Automatic import

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#4]
Нужно настроить автоматический импорт scss и js, чтобы не приходилось руками добавлять импорты или менять пути, если что-то изменится.

**Comment by Nirall** [comment]
C автоматическим импортом скриптов для datepicker'а пока не получается, импортирую напрямую.

**Comment by Feinminen** [comment]
Ты сейчас реализовал импорт картинок через js файл в каждой папке.
![image](https://user-images.githubusercontent.com/44312820/93297283-2c582100-f81b-11ea-9fb9-6fdb8188b473.png)
все jpg/png/svg/ico тоже можно сделать через автоматический импорт, чтобы не было бойлер-плейта

**Comment by Nirall** [comment]
Подправил

**Comment by Nirall** [comment]
Подправил, убрал инлайн лоадер для фавиконс. Смотреть этот коммит, сами коммиты удалил, но ссылки остались

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/93734837-1d031a00-fc05-11ea-8e8c-2e6f40e6ab0c.png)
Можно же было через один importAll сделать все импорты, они всё равно с одной папки импортят

**Comment by Nirall** [comment]
Объединил в 1 импорт
