### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#5]
Добавь, пожалуйста, в папку с PP настройку его окна.
![image](https://user-images.githubusercontent.com/44312820/91119991-cc100c80-e6be-11ea-947b-cd525aa683d8.png)

И ещё, подскажи пожалуйста, под какое разрешение верстался проект?

**Comment by Nirall** [comment]
Верстал под ширину 1440px. Добавил файл "settings.jpg" в папке PerfectPixel -это скриншот настройки окна .

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/92346993-cc65ca00-f0f8-11ea-86c7-bad463399c4c.png)

На лэндинг пэйдже в форме в инпуте появилась лишняя рамка.

Также в форме нужно чуть-чуть поправить по перфект пикселю позиционирование текста в кнопке и инпутах
![image](https://user-images.githubusercontent.com/44312820/92347103-1949a080-f0f9-11ea-992e-54438c28323c.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/92347294-d76d2a00-f0f9-11ea-9ba2-a6a941d73f07.png)

**Comment by Feinminen** [comment]
По пиксельперфекту допускаются небольшие расхождения в тексте, т.к. порой крайне тяжело настроить все парметры также как в макете, т.к. шрифты могу отличаться, но не более того, всё остальное должно быть +- идеально, так чтобы этого особо не было заменто в PP

**Comment by Feinminen** [comment]
По-хорошему, нужно сразу продумывать то как макет будет выглядеть на экранах как меньше, так и больше верстаемого.
![image](https://user-images.githubusercontent.com/44312820/92347641-e99b9800-f0fa-11ea-8a23-5a0cf2b9734e.png)

На экранах больше сейчас хэдер и футер расползаются, а основная картинка фона бэкраунда остаётся неизменной, за счёт чего появляются пустые белые поля.
Из того как сделан макет, можно явно вывести, что хедер форма и футер должны идти по одной линии, а картинка должна растягиваться на всю ширину экрана.

На больших экранах должно быть также и без полей 
![image](https://user-images.githubusercontent.com/44312820/92347699-16e84600-f0fb-11ea-9acf-a97ed48ea31b.png)

**Comment by Nirall** [comment]
Подправил. Часть изменений по блокам была в предыдущем коммите, когда рефакторил блоки. В этом коммите рефаткторинг для экранов шире 1440px

**Comment by Feinminen** [comment]
На странице search room в карточках явно используются другие шрифты + нет паддингов у индикаторов фотографий.
![image](https://user-images.githubusercontent.com/44312820/93735254-90f1f200-fc06-11ea-9948-864fec9dd4d2.png)
![image](https://user-images.githubusercontent.com/44312820/93735286-acf59380-fc06-11ea-8424-5bc88c5b81a7.png)

**Comment by Feinminen** [comment]
В целом на всех страничках есть какие-то пробелмы с шрифтами, то где-то не та толщина шрифта, то лишняя опасити. Погляди на всех страничках чтобы всё ок было, плез.

**Comment by Nirall** [comment]
Для крупных заголовков h1, h2  в макете используется шрифт Quicksand. Для кириллицы шрифт с таким же начертанием не нашел, гугловский сильно отличается, попадался еще один quicksand с засечками. Вылепливал его из Montserrat, но нормально свести не получается.
