### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#7]
Чтобы не было подобного рода ошибок в проектах (тут должна быть одна 'p') - можно использовать любое расширение для IDE с проверкой правописания(хотя бы английского). Например, 'Code Spell Checker' для VS-code.
![image](https://user-images.githubusercontent.com/44312820/91120726-8b18f780-e6c0-11ea-932d-975f321b0dd8.png)

**Comment by Nirall** [comment]
Понял, Spell Checker поставил. Код править не надо?

**Comment by Feinminen** [comment]
Лучше подправить, коненчо :)

**Comment by Nirall** [comment]
Подправил орфографические ошибки

**Comment by Feinminen** [comment]
Сейчас достаточно много элементов/блоков/модификаторов именованы не по правилам БЭМ-а и совершенно не семантически: в названиях есть неочевидные сокращения(lh18px, item-i, butt), использование в названиях тэгов(h3, ul, li), тоже нужно поглядеть по всему проекту

**Comment by Feinminen** [comment]
А также нужно будет поправить названия подключенных картинок:
1) они должны именоваться в стиле lowercase-hyphenated
2) у них должны быть понятные названия
