### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by Feinminen** [Nirall/FSD_hotel#8]
БЭМ-блоки следует выделять в отдельные компоненты. Один блок - это один компонент, у которого своя папка с собственными pug, scss и js файлами(если необходимо).

Сейчас у тебя достаточно много компонентов, в которых сразу большое количество блоков.
Также по БЭМ-у всех html элементов должен быть свой класс, без классов допускаются только инлайновые элементы без семантики(инлайновые обертки, напрмер)

Также сейчас никак не используеешь преимущества scss в БЭМ. В папке конкретного блока должен лежать ТОЛЬКО один pug, scss и если нужно js файл. У тебя сейчас ещё идёт разбиение на папки для стилей элементов внутри блока, что абсолютно не нужно. Должен быть один стилевой файл для блока.
Все стили можно и нужно писать вот таким образом:
![image](https://user-images.githubusercontent.com/44312820/91121956-3aef6480-e6c3-11ea-8ef7-7fd372e4a572.png)
(скрин просто для примера)

Также в БЭМ не допускается вешать стили на тэги.
![image](https://user-images.githubusercontent.com/44312820/91122021-696d3f80-e6c3-11ea-9a8f-a1ac80f989c6.png)

**Comment by Nirall** [comment]
Подправил, за исключением блока "appartment-card" - переиспользую его элемент "__info" в блоке "appartments-finder-check" и блока "footer-large" - использую элемент "__list" чтобы код не дублировать. Эти блоки тоже подправить?

**Comment by Feinminen** [comment]
По БЭМ-у вообще не должно быть такого, что один элемент используется в разных блоках - это недопустимо.
В таких случаях можно делать из элемента блок и просто импортить миксин с блоком где нужно.
Элемент всегда зависит от своего одного и единственного блока.
![image](https://user-images.githubusercontent.com/44312820/91555966-25e13280-e95c-11ea-8483-80a8320cb400.png)

**Comment by Feinminen** [comment]
Название папки/файла/миксина и блока всегда должны совпадать
![image](https://user-images.githubusercontent.com/44312820/91557346-8a04f600-e95e-11ea-8154-e2510c029b30.png)

**Comment by Feinminen** [comment]
Также на этом скрине внутри одно блока используется сразу два других - это тоже недопустимо.
Внутри content-registration - лежит wrapper-registration-form и wrapper-in-form.
Для одной папки и одного файла всегда будет только один блок.

**Comment by Feinminen** [comment]
С стилями соответсвенно всё то же самое. В одном файле должны быть стили только одного блока 
![image](https://user-images.githubusercontent.com/44312820/91557596-f253d780-e95e-11ea-9ca7-0bf5d3283d28.png)

**Comment by Feinminen** [comment]
Погляди все замечания по всему проекту, пожалуйста, они явно не в одном файле.

**Comment by Nirall** [comment]
> Также на этом скрине внутри одно блока используется сразу два других - это тоже недопустимо.
> Внутри content-registration - лежит wrapper-registration-form и wrapper-in-form.
> Для одной папки и одного файла всегда будет только один блок.
Так это же страница а не блок. Просто там кроме 2-х форм больше ничего нет

**Comment by Nirall** [comment]
> С стилями соответсвенно всё то же самое. В одном файле должны быть стили только одного блока
> ![image](https://user-images.githubusercontent.com/44312820/91557596-f253d780-e95e-11ea-9ca7-0bf5d3283d28.png)

Это то же страница. Или все равно надо оборачивать единым блоком?

**Comment by Nirall** [comment]
Подправил.  Рефакторил в основном пейджи, по блокам то что попадалось тоже подредактировал.

**Comment by Feinminen** [comment]
> > Также на этом скрине внутри одно блока используется сразу два других - это тоже недопустимо.
> > Внутри content-registration - лежит wrapper-registration-form и wrapper-in-form.
> > Для одной папки и одного файла всегда будет только один блок.
> 
> Так это же страница а не блок. Просто там кроме 2-х форм больше ничего нет

В БЭМ нет такого понятния как 'страница'. Любой html элемент на страние может быть только блоком/элементом или модификтором.
Т.е. в соответсвии с БЭМ это два разных блока и, соответсвенно, такой подход не является допустимым.
Сделано это, в основном, для того, чтобы можно было отслеживать где для какого блока лежат стили/скрипты/верстка, что в свою очередь очень помогает поддерживать код, т.к. всё можно легко найти просто поиском по проекту, а также так крайне просто найти где лежат стили для конкретного блока.
Как кто-то должен понять, что в файле lending-page.scss лежат стили именно для блоков phrase-of-day и content-landing-page? :)

**Comment by Feinminen** [comment]
В БЭМ бывают модификторы только двух типов: булевый и ключ-значение. Булевы используют, когда важно только наличие или отсутствие модификатора, а его значение несущественно и это практически всегда отглагольное прилагательное ('disabled', 'focused' и т.д.).  А ключ-значение, соответсвенно используют, когда важно значение модификатора и у него всегда есть ключ (например size) и значение (например small). 
Сейчас множество модификаторов не соответствует БЭM: '_sign-in', '_grey', '_body' и т.д.

**Comment by Feinminen** [comment]
В папке button сейчас лежат только стили, а миксина нет.
Все замечания, которые я писал выше - нужно поправить по всему проекту, сейчас в блоках осталось достаточно много ошибок по БЭМ-у

**Comment by Feinminen** [comment]
В файле index.scss сейчас нет ниодного допустимого стиля по БЭМ.
Максимум, что у нас допускается делать общего по проекту - ставить общие стили для шрифтов на html, медиазапросы по размеру шрифта и, также, в универсальном селекторы примерно такой свод стилей:
```
*
  margin: 0
  padding: 0
  box-sizing: border-box
```
, чтобы каждый раз не занулять дефолтные маргины и падиннги элементов и не переключать box-sizing на border-box, т.к. он стандартный по проекту, всё  остальное запрещено, также как и в БЭМ.

Также, всё что связанно с подключением шрифтов - нужно будет вынести в отдельный файл.
А ещё сейчас у тебя в проекте все переменные дублируются, т.к. они заданы в index.scss и в variables.scss.

**Comment by Nirall** [comment]
> Максимум, что у нас допускается делать общего по проекту - ставить общие стили для шрифтов на html, медиазапросы по размеру шрифта и, также, в универсальном селекторы примерно такой свод стилей:

А как же заголовки? Для каждого блока прописывать правила для заголовков?

Почему в БЭМе не используют более простую семантику со вложенными стилями с SCSS? Как пример:
```
.block {
  color: red;
  
  .element {
    color: green;
  }
}
```

Это бы преобразовывалось в
```
.block {
  color: red;
}

.block  .element {
  color: green;
}
```
Все стили изолированы внутри блока, конфликтов быть не должно. Селектор с большим приоритетом случайно не напишешь. Зато семантику бы разгрузило. Если в SCSS за счет символа родительского селектора & читаемость еще норм, то в HTML как-то  совсем грустно. Можно получить что-то вроде:
`.apartment-form__title-price-wrapper.apartment-form__title-price-wrapper_size-big.js-apartment-form__title-price-wrapper`

**Comment by Nirall** [comment]
Прошелся по блокам, страницы UI-kit пока не трогал, index.scss подправил.

**Comment by Feinminen** [comment]
> > Максимум, что у нас допускается делать общего по проекту - ставить общие стили для шрифтов на html, медиазапросы по размеру шрифта и, также, в универсальном селекторы примерно такой свод стилей:
> 
> А как же заголовки? Для каждого блока прописывать правила для заголовков?

Заголовки тоже нужно конфигурить под каждый блок отдельно, либо можно сделать отдельный дженерик блок-миксин с заголовками.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/93736194-bf250100-fc09-11ea-9524-d41ee3fb3972.png)
Такие модификаторы по БЭМ недопустимы, они не должны указывать на конкретные css правила, но при этом и не должны быть абстрактными. Модификаторы должны описывать внешний вид.
![image](https://user-images.githubusercontent.com/44312820/93736282-0a3f1400-fc0a-11ea-9692-b015bdae5746.png)

**Comment by Feinminen** [comment]
А булевые модификаторы именуются через два нижних подчеркивния, т.е. должно быть ```_size_small```, а не ```_size-small```

**Comment by Feinminen** [comment]
Также по БЭМ нельзя давать внешние отступы блокам, это также не означает, что внешние отступы можно делать через паддинги)
Отступы нужно делать через элементы - обертки блоков.
Т.е. отступами, допустим, карточек аппартаментов не должен заниматься блок apartment-card. Их должен выставлять элемент обертка блока, т.е. допустим у тебя есть пэйджа appartments, в которой лежат карточки, и у этих карточек просто будут обертки-элементы appartments__card(элемент блока аппартментс).
Это нужно для того, чтобы потом эти карточки и любые блоки можно было без проблем переисользовать и не беспокоиться за захардкоженные отступы.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94223558-79727c00-ff1a-11ea-8905-7c772752605e.png)

Тут модификатор должен быть булевым, а не ключ значение. Т.к. тут не важно значение ключа - важно только отсутсвие или наличие этого модификатора. Обычно в таких случаях называют что-то типа '_without-arrows' или можно непосредственно на стрелки сделать модификатор 'disabled'.
Про наши стандарты именования можно почитать вот [тут](https://github.com/fullstack-development/front-end-best-practices/blob/8bbcc186a97684cdb0536f7fee18054d417f306a/CSS/README.md) в разделе БЭМ

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94223965-72983900-ff1b-11ea-8e12-308f8e5e1e8d.png)
В таких случаях лучше писать вот так, чтобы было сразу видно к какому элементу относится модификатор.
![image](https://user-images.githubusercontent.com/44312820/94224010-90659e00-ff1b-11ea-93b5-b6f1da67db32.png)

**Comment by Feinminen** [comment]
Адишники по БЭМ тоже не допускаются.
![image](https://user-images.githubusercontent.com/44312820/94224123-c7d44a80-ff1b-11ea-8d48-2683c05387c3.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94224398-6a8cc900-ff1c-11ea-9255-3eeafcd988bf.png)
Тут ты мнеяешь стили сразу четырех блоков, если с либами это допустимо(хотя нужно отдельно будет смотреть, чтобы +- БЭМ соотвествовало), то свои блоки явно так менять нельзя.

**Comment by Nirall** [comment]
> Тут ты мнеяешь стили сразу четырех блоков, если с либами это допустимо(хотя нужно отдельно будет смотреть, чтобы +- БЭМ соотвествовало), то свои блоки явно так менять нельзя.

Тогда создавать различные модификаторы для блоков, для конкретных случаев? Потому что к примеру в каком-нибудь блоке "form" встраиваемый блок "dropdown" должен менять свою ширину при ширине экрана < 400px, а в другом блоке "card" тот же встраиваемый блок должен делать это при ширине экрана < 350px.

**Comment by Nirall** [comment]
Хотя с шириной наверно не самый удачный пример, но смысл в том что один и тот же блок должен к примеру вести себя по разному в зависимости от того какой блок его встраивают.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94520616-c629c000-0256-11eb-8251-3f24ec0b5c75.png)
Тут сразу несколько нюансов:
1) Photos, а не fotos :)
2) photos-left, photos-right - некорректные занвания, из-за того что right/left это прилагательные/наречия и они не указывают на то что элемент описывает. (или, как минимум, должен быть другой порядок слов)
3) image1, image2 - тоже некорректные названия.
Вообще все элементы с описанием комнат можно вынести в один блок room-details или что-то тип того и просто передавать туда массив с нужными тайтлами и картинками.

![image](https://user-images.githubusercontent.com/44312820/94520979-70094c80-0257-11eb-8b18-d8816b767732.png)
Вот так, примерно.

**Comment by Nirall** [comment]
> 1. Photos, а не fotos :)

Мда-а XD, а я понять не мог что меня там смущало. Переделал блок info-apartment чтоб массив принимал

**Comment by Nirall** [comment]
Подключение блока info-appartment в ui-kit подправил в коммите к #11

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94882872-57857600-0493-11eb-9fa0-f0931dba321c.png)
clear/apply - это глаголы. Элементы/блоки должны описывать иммено сущность и быть существительным, если это кнопки, то apply-button/clear-button соответсвенно.

**Comment by Feinminen** [comment]
Я сейчас не буду говорить всё исправлять, но на будущее, старайся как можно меньше сокращений использовать. Есть моменты, когда это допустимо, но там очень тонкая граница, есть сокращения, которые будут понятны 99% разрабов, а есть те, которые значительно меньшему количеству. И уж лучше дописать пару символов в класс/переменную, чем вносить сокращениями какую-то неопределённость.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/94883226-4e48d900-0494-11eb-8491-e2c37b2b73ce.png)
Ещё остались некорректные модификаторы.

**Comment by Feinminen** [comment]
Не помню писал ли я, но в случае, когда один из аргументов функции не используется - по код конвеншену его именуют нижним подчеркиванием(причем для первого аргумента - одно подчеркивание, для второго два и т.д.):
this.header((_, el) => {}) - тогда IDE и линтеры не будут ругаться на неиспользуемый аргумент.

![image](https://user-images.githubusercontent.com/44312820/95285519-31911480-088b-11eb-855d-3148918819dd.png)
